import React, { useState } from "react"
import { Link } from "react-router-dom"
import { motion, useReducedMotion } from "framer-motion"

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.6, delay, ease: [0.4, 0, 0.2, 1] },
})

const SECTIONS = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: [
      "By accessing or using Hi-SEO (the Service), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.",
      "Hi-SEO is operated by Hi-SEO Technologies Ltd, a company registered in Nigeria. These terms apply to all users of the platform including free and paid plan subscribers.",
      "We reserve the right to update these terms at any time. We will notify users of significant changes via email or an in-app notification. Your continued use of the Service after changes take effect constitutes your acceptance of the revised terms.",
    ],
  },
  {
    id: "account",
    title: "Account Registration and Security",
    content: [
      "To access Hi-SEO, you must create an account by providing accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials.",
      "You must be at least 18 years old to create an account. By registering, you confirm that all information you provide is truthful and accurate.",
      "You are responsible for all activity that occurs under your account. If you suspect unauthorized access, notify us immediately at security@hi-seo.com.",
      "We reserve the right to suspend or terminate accounts that violate these terms, provide false information, or engage in abusive behavior toward our platform or team.",
    ],
  },
  {
    id: "service",
    title: "Use of the Service",
    content: [
      "Hi-SEO grants you a limited, non-exclusive, non-transferable license to use the Service for your personal or business SEO needs, subject to these terms.",
      "You agree not to use the Service to: (a) violate any laws or regulations, (b) infringe on intellectual property rights, (c) transmit malware or harmful code, (d) attempt to reverse engineer or extract our proprietary data, or (e) resell access to the platform without written permission.",
      "You may not use automated systems or bots to access the Service in ways that place excessive load on our infrastructure or circumvent rate limits.",
      "All SEO data, reports, and insights generated by Hi-SEO are for your internal business use. You may not redistribute, resell, or publish our proprietary data without explicit written permission.",
    ],
  },
  {
    id: "payment",
    title: "Payments and Billing",
    content: [
      "Paid plans are billed monthly or annually depending on your selected billing cycle. All prices are listed in Nigerian Naira (NGN) and payments are processed via Paystack.",
      "By subscribing to a paid plan, you authorize Hi-SEO to charge your selected payment method on a recurring basis until you cancel your subscription.",
      "We offer a 7-day refund policy on all paid plans. If you are not satisfied, contact us at billing@hi-seo.com within 7 days of payment and we will issue a full refund.",
      "Prices are subject to change with 30 days advance notice to existing subscribers. Price changes do not affect your current billing period.",
      "Failed payments may result in temporary suspension of your account. We will attempt to notify you before any service interruption.",
    ],
  },
  {
    id: "data",
    title: "Your Data and Content",
    content: [
      "You retain full ownership of any content, data, or information you input into Hi-SEO. We do not claim ownership of your projects, keywords, reports, or any other data you create.",
      "By using Hi-SEO, you grant us a limited license to process your data solely for the purpose of providing the Service to you.",
      "We implement industry-standard security measures to protect your data including encryption at rest and in transit, and row-level database security that prevents any user from accessing another user data.",
      "Upon account deletion, your personal data will be removed from our systems within 30 days. Some anonymized usage data may be retained for analytics purposes.",
    ],
  },
  {
    id: "intellectual",
    title: "Intellectual Property",
    content: [
      "Hi-SEO and all its contents including software, algorithms, designs, text, and data are the intellectual property of Hi-SEO Technologies Ltd and are protected by applicable copyright and intellectual property laws.",
      "Our trademarks, logos, and brand identity may not be used without our written permission.",
      "You may not copy, modify, distribute, or create derivative works based on our platform or its underlying technology.",
      "If you believe any content on Hi-SEO infringes your intellectual property rights, please contact us at legal@hi-seo.com with full details of your claim.",
    ],
  },
  {
    id: "disclaimers",
    title: "Disclaimers and Limitations",
    content: [
      "Hi-SEO is provided on an as-is basis. While we strive for accuracy in all data and insights we provide, we cannot guarantee that search volume figures, keyword difficulty scores, or ranking estimates are 100 percent accurate.",
      "SEO outcomes depend on many factors outside our control including Google algorithm changes, competition, and the quality of your implementation. We do not guarantee specific ranking results from using our platform.",
      "To the maximum extent permitted by law, Hi-SEO shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service.",
      "Our total liability to you for any claims arising from these terms or your use of the Service shall not exceed the amount you paid to Hi-SEO in the three months preceding the claim.",
    ],
  },
  {
    id: "termination",
    title: "Termination",
    content: [
      "You may cancel your account at any time from your account settings. Cancellation takes effect at the end of your current billing period for paid plans.",
      "We reserve the right to suspend or terminate your account immediately if we determine you have violated these terms, engaged in fraudulent activity, or your actions pose a risk to other users or our platform.",
      "Upon termination, your right to use the Service ceases immediately. Data retention policies described in the Your Data section still apply.",
    ],
  },
  {
    id: "governing",
    title: "Governing Law",
    content: [
      "These Terms of Service are governed by the laws of the Federal Republic of Nigeria. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of Lagos State, Nigeria.",
      "If any provision of these terms is found to be unenforceable, the remaining provisions will continue in full force and effect.",
      "These terms constitute the entire agreement between you and Hi-SEO regarding your use of the Service and supersede all prior agreements.",
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    content: [
      "If you have questions about these Terms of Service, please contact us at legal@hi-seo.com or through our Contact page.",
      "For billing disputes, contact billing@hi-seo.com. For security concerns, contact security@hi-seo.com.",
      "Hi-SEO Technologies Ltd, Lagos, Nigeria.",
    ],
  },
]

export default function Terms() {
  const shouldReduceMotion = useReducedMotion()
  const [activeSection, setActiveSection] = useState("")

  return (
    <div className="overflow-x-hidden">

      {/* HERO */}
      <section
        className="relative py-24 overflow-hidden"
        style={{ background: "linear-gradient(135deg, #1239a8 0%, #07123f 100%)" }}
      >
        <div className="absolute inset-0 bg-grid-overlay opacity-40" />
        <div className="absolute inset-0" style={{ background: "radial-gradient(ellipse 60% 50% at 50% 50%, rgba(59,130,246,0.2) 0%, transparent 70%)" }} />
        <div className="hero-blob hero-blob-blue animate-blob" style={{ width: "400px", height: "400px", top: "-100px", right: "-80px", opacity: 0.25 }} />

        <div className="section-container relative z-10">
          <motion.div
            initial={shouldReduceMotion ? {} : { opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-2xl"
          >
            <div
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold mb-6"
              style={{ background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.15)", color: "rgba(255,255,255,0.8)" }}
            >
              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
              Legal document
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight mb-4">
              Terms of Service
            </h1>
            <p className="text-blue-200/60 text-lg leading-relaxed mb-6">
              Please read these terms carefully before using Hi-SEO. By using our platform you agree to be bound by these terms.
            </p>
            <div className="flex items-center gap-4 text-sm text-white/40 font-medium">
              <span>Last updated: January 28, 2025</span>
              <span>•</span>
              <span>Effective: January 28, 2025</span>
            </div>
          </motion.div>
        </div>

        <div className="absolute bottom-0 left-0 right-0">
          <svg viewBox="0 0 1440 80" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" className="w-full h-16">
            <path d="M0 80L60 72C120 64 240 48 360 40C480 32 600 32 720 37.3C840 43 960 53 1080 58.7C1200 64 1320 64 1380 64L1440 64V80H1380C1320 80 1200 80 1080 80C960 80 840 80 720 80C600 80 480 80 360 80C240 80 120 80 60 80H0Z" fill="white" />
          </svg>
        </div>
      </section>

      {/* CONTENT */}
      <section className="py-16 bg-white">
        <div className="section-container">
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-10 max-w-6xl mx-auto">

            {/* Sidebar nav */}
            <div className="lg:col-span-1">
              <div className="sticky top-24">
                <p className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4">
                  Table of Contents
                </p>
                <nav className="space-y-1">
                  {SECTIONS.map((section, i) => (
                    <a
                      key={section.id}
                      href={`#${section.id}`}
                      onClick={() => setActiveSection(section.id)}
                      className="flex items-center gap-2.5 px-3 py-2 rounded-xl text-sm font-semibold transition-all duration-200"
                      style={{
                        color: activeSection === section.id ? "#3b82f6" : "#64748b",
                        background: activeSection === section.id ? "rgba(59,130,246,0.08)" : "transparent",
                      }}
                    >
                      <span
                        className="w-5 h-5 rounded-md flex items-center justify-center text-[10px] font-black shrink-0"
                        style={{
                          background: activeSection === section.id ? "rgba(59,130,246,0.15)" : "#f1f5f9",
                          color: activeSection === section.id ? "#3b82f6" : "#94a3b8",
                        }}
                      >
                        {i + 1}
                      </span>
                      {section.title}
                    </a>
                  ))}
                </nav>

                <div
                  className="mt-8 p-4 rounded-2xl"
                  style={{ background: "rgba(59,130,246,0.06)", border: "1px solid rgba(59,130,246,0.12)" }}
                >
                  <p className="text-xs font-bold text-slate-700 mb-2">Questions about our terms?</p>
                  <p className="text-xs text-slate-500 mb-3">Our team is happy to explain anything in plain language.</p>
                  <Link
                    to="/contact"
                    className="text-xs font-bold text-blue-600 hover:text-blue-700 flex items-center gap-1 transition-colors"
                  >
                    Contact us
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                      <path d="M5 12h14M12 5l7 7-7 7" />
                    </svg>
                  </Link>
                </div>
              </div>
            </div>

            {/* Main content */}
            <div className="lg:col-span-3 space-y-8">
              {/* Summary box */}
              <motion.div
                {...fadeUp()}
                className="p-6 rounded-2xl"
                style={{ background: "rgba(249,115,22,0.06)", border: "1px solid rgba(249,115,22,0.15)" }}
              >
                <div className="flex items-start gap-3">
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                    style={{ background: "rgba(249,115,22,0.15)" }}
                  >
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#f97316" strokeWidth="2">
                      <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-sm font-black text-slate-900 mb-2">Plain language summary</h3>
                    <p className="text-sm text-slate-600 leading-relaxed">
                      By using Hi-SEO you agree to use it lawfully, keep your account secure, and pay for your plan. We own the platform, you own your data. We offer a 7-day refund policy. These terms are governed by Nigerian law.
                    </p>
                  </div>
                </div>
              </motion.div>

              {SECTIONS.map((section, i) => (
                <motion.div
                  key={section.id}
                  id={section.id}
                  {...fadeUp(i * 0.05)}
                  className="scroll-mt-24"
                >
                  <div
                    className="p-7 rounded-2xl border border-slate-100 hover:border-blue-100 transition-colors duration-200"
                  >
                    <div className="flex items-center gap-3 mb-5">
                      <span
                        className="w-8 h-8 rounded-xl flex items-center justify-center text-sm font-black"
                        style={{ background: "linear-gradient(135deg, #1d4ed8, #06b6d4)", color: "white" }}
                      >
                        {i + 1}
                      </span>
                      <h2 className="text-xl font-black text-slate-900">{section.title}</h2>
                    </div>
                    <div className="space-y-4">
                      {section.content.map((paragraph, pi) => (
                        <p key={pi} className="text-sm text-slate-600 leading-relaxed">
                          {paragraph}
                        </p>
                      ))}
                    </div>
                  </div>
                </motion.div>
              ))}

              <motion.div {...fadeUp()} className="p-6 rounded-2xl border border-slate-200 bg-slate-50 text-center">
                <p className="text-sm text-slate-500 font-medium">
                  These terms were last updated on January 28, 2025. If you have questions, contact us at{" "}
                  <a href="mailto:legal@hi-seo.com" className="text-blue-600 font-semibold hover:underline">
                    legal@hi-seo.com
                  </a>
                </p>
              </motion.div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
